Feature delete
KelwayHao/FlightsApplication pull request #2
Opened 2022-04-04 19:23 UTC by KelwayHao

2022-04-04 20:33 UTC, Vinny94051 requested changes

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/domain/models/FlightTicket.kt
>          CHILD("Child")
я вроде говорил это в строки вынести

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/datapickmanager/DataPickerManager.kt
> +    private fun timePickTime(textView: TextView, calendar: Calendar, context: Context) {
почему тут констекст в параметрах остался, если он уже в конструкторе?

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/HistoryFragment.kt
> +    private val viewTicketModel: HistoryFragmentViewModel by viewModel<HistoryFragmentViewModel>()
либо тип явно не указывай либо в генерике убери HistoryFragmentViewModel

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/HistoryFragment.kt
> +                    showSnack(requireActivity().getString(R.string.remote_success), requireView())
а что будет если удаление пройдет не успешно? ты сейчас это никак не мониторишь на самом деле, я бы как минимум тост показывал после завершения корутины (в идеале чекать действительно ли удалилось но вы этого пока не умеете, так что хватит простого ожидания) у корутины есть метод invokeOnCompetion или invokeAfterComplete точн не помню

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +    private val viewModel: FlightFragmentViewModel by viewModel<FlightFragmentViewModel>()
явно не указывать или убрать из генерика

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +    }
зачем это делать через листнеры? лучше просто в лайв дату событие отправить мол все ок и по подписке показывать снек

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +        val dataPicker = DataPickerManager(requireContext())
лучше в поле вынести, будет крашится тк нет контекста, если не юзать by lazy

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +        val d = idTicket
нейминг переменной шикарный (нет) 👎

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/listeners/ValidationListener.kt
> +interface ValidationListener {
юзлес штука (почему описал выше)

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/FlightFragmentViewModel.kt
> +                validListener.validationListener(R.string.message_flight_success)
👎

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/FlightFragmentViewModel.kt
> +        validListener: ValidationListener
👎

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +        val idTicket: Long = viewModel.getSize()
зачем создание id делать тут? тебе до момента сохранения id вообще не нужен, надо его прямо в репе генерить

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/FlightFragmentViewModel.kt
> +        idTicket: Long,
👎

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/FlightFragmentViewModel.kt
> +        return !(departure.isEmpty() ||
чтоб не ставить тут оператор "не" можно заюзать методы isNotEmpty

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/HistoryFragmentViewModel.kt
> +            getFlightTickets()
что будет если удаление произойдет медленнее, чем получение всех данных из таблицы? На экране отобразится не актуальный (с удаленым айтемом) список (invokeOnCompetition в помосч)

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Constant.kt
>          const val VERSION_DB = 1
это должно быть в AppDatabase

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +fun SwitchMaterial.checkPassengerAge(): FlightTicket.PassengerAge {
выглядит как приватный экстеншн внутри фрагмента, а не общедоступный

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +        .setPositiveButton("Yes") { dialogMessage, _ ->
в условии к дз не такие текста для кнопок указаны (в ресурсы)

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +        .setNegativeButton("No") { dialogMessage, _ ->
👎

2022-04-04 20:33 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Mappers.kt
> +    return FlightTicket.PassengerAge.valueOf(this.uppercase())
this не нужен

2022-04-04 20:50 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +        val d = idTicket
Это я для дебагга делал, забыл убрать

2022-04-04 21:11 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/domain/models/FlightTicket.kt
>          CHILD("Child")
Как тогда получить строки, без контекста? getString и getResource не сработают. Как варик кидать int значение строки, а дальше где нужно использовать getString

2022-04-04 21:24 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/utils/Mappers.kt
> +    return FlightTicket.PassengerAge.valueOf(this.uppercase())
Done

2022-04-04 21:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/datapickmanager/DataPickerManager.kt
> +    private fun timePickTime(textView: TextView, calendar: Calendar, context: Context) {
Done

2022-04-04 21:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/HistoryFragment.kt
> +    private val viewTicketModel: HistoryFragmentViewModel by viewModel<HistoryFragmentViewModel>()
Done

2022-04-04 21:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +    private val viewModel: FlightFragmentViewModel by viewModel<FlightFragmentViewModel>()
Done

2022-04-04 21:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/RegistrationFragment.kt
> +        val dataPicker = DataPickerManager(requireContext())
Done

2022-04-05 06:21 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/presentation/viewmodel/FlightFragmentViewModel.kt
> +        return !(departure.isEmpty() ||
done

2022-04-05 06:24 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/utils/Constant.kt
>          const val VERSION_DB = 1
done

2022-04-05 06:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +        .setNegativeButton("No") { dialogMessage, _ ->
done

2022-04-05 06:25 UTC, KelwayHao commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +        .setPositiveButton("Yes") { dialogMessage, _ ->
done

2022-04-09 12:16 UTC, Vinny94051 approved these changes

2022-04-09 12:16 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/utils/Extensions.kt
> +fun Fragment.dialog(message: String, context: Context, deleteFlight: () -> Unit, updateFlight: () -> Unit) {
2 лямбды это ничего страшного, но лучше было их назвать onPositiveButtonClick и onNegativeButtonCLicked

2022-04-09 12:16 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapplication/presentation/fragment/HistoryFragment.kt
> +            )
```suggestion
        dialog(
            message = getString(R.string.title_dialog_message),
            context = requireContext(),
            onPositiveButtonClick = {
                viewTicketModel.removeItem(position)?.let { flightTicket ->
                    viewTicketModel.deleteFlightTicket(flightTicket)
                }
                recyclerFlights.adapter?.notifyItemRemoved(position)
            },
            onNegativeButtonClick = { viewTicketModel.getFlightTickets() }
        )
```
ну и вот такое форматирование было бы приятнее читать

2022-04-09 20:11 UTC, merged